---
title: "Real-time Autonomous Parking in Unstructured Scenarios with an Indirect Optimal Control Approach"
author: [ "Edoardo Pagot", "Mattia Piccinini", "Alice Plebe", "Enrico Bertolazzi", "Francesco Biral"]
publication: "Behavior-Driven Autonomous Driving in Unstructured Environments (BADUE), IEEE/RSJ International Conference on Intelligent Robots and Systems (IROS)"
categories: 
  - "Publications"
  - "Workshop Articles"
type: workshop
url_source: 
url_preprint: 
journ: "IROS Workshop"
# issue: 
# page: 
# doi: 
year: 2022
video: U2mRTzmFj9w
# image: ""
---

## Video

{{< video https://www.youtube.com/watch?v=U2mRTzmFj9w >}}

## Abstract <!-- omit in toc -->

This paper presents a framework to generate in real-time autonomous parking maneuvers for generic and unstructured parking scenarios. Our method is based on the solution of minimum-time optimal control problems by means of an indirect approach. In a single optimization, the framework computes parking maneuvers composed of two or more segments of forward and reverse driving. The trajectory planning tasks are solved in real-time, and a fine grid is used to discretize the domain of the optimal control problems, resulting in accurate and collision-free solutions. Moreover, we introduce a novel method to deal with static obstacles in the optimal control problems, using penalty functions defined as regularized three-dimensional clip functions. The results show the effectiveness of our approach in various scenarios with narrow parking spots.
