---
title: "DRIVEWISE Research Group"
---

Welcome to the DRIVEWISE Research Group website! 

Welcome to the DRIVEWISE research group at the <a href="https://www.dii.unitn.it/">Department of Industrial Engineering</a> of the <a href="https://www.unitn.it/">University of Trento</a>, led by Professors Francesco Biral and Enrico Bertolazzi.

Our collaborative team is dedicated to advanced applied mechanics, autonomous systems, artificial intelligence, dynamics and control, and optimization.
Through this rich blend of experience and knowledge, we can tackle complex problems focusing on intelligent mobility, autonomous driving, and Advanced Driving Assistance Systems (ADAS).
Embedded in our DNA is a commitment to exploring new frontiers, as demonstrated by our active participation in impactful European projects.

Join us on a journey where curiosity and innovation converge, shaping the future of intelligent mobility. Discover a world where we redefine what's possible at the exciting crossroads of applied mechanics and autonomous systems.
