---
title: "Fast Planning and Tracking of Complex Autonomous Parking Maneuvers With Optimal Control and Pseudo-Neural Networks"
author: [ "Edoardo Pagot", "Mattia Piccinini", "Enrico Bertolazzi", "Francesco Biral"]
publication: "IEEE Access - Volume 11, pp. 124163-124180, 2023"
categories: 
  - "Publications"
  - "Journal Articles"
type: journal
url_source: 
url_preprint: 
journ: "IEEE Access"
issue: Volume 11
page: pp. 124163-124180
doi: 10.1109/ACCESS.2023.3330431
year: 2023
video: U2mRTzmFj9w
# image: ""
bibtex: bibtex.txt
---

## Video

{{< video https://www.youtube.com/watch?v=U2mRTzmFj9w >}}


## Abstract <!-- omit in toc -->

This paper presents a framework to plan and execute autonomous parking maneuvers in complex parking scenarios. We formulate a minimum-time optimal control problem for trajectory planning, using an indirect optimal control approach. A novel smooth penalty function is devised for collision avoidance with optimal control, and an effective technique is adopted to compute an initial solution guess. The trajectory planning tasks are solved with low computational times, and a dense mesh is used to discretize the domain of the optimal control problems, resulting in accurate collision-free solutions. The planned parking maneuvers are tracked with an original pseudo-neural feedforward-feedback steering controller, which outperforms other techniques from the literature, and a feedback longitudinal controller, to drive a realistic 14-degree-of-freedom vehicle simulator. We validate the planning and tracking algorithms in challenging narrow parking scenarios, including reverse, parallel and angle parking, and unstructured environments. The framework robustness is assessed by changing the vehicle mass, the road adherence conditions, and by introducing measurement noise with realistic sensor models. A video of the trajectory planning and tracking results is available as supplementary material.

## Cite this work

```{=html}
<div style="position: relative; width: 100%; padding-bottom: 40%; ">
  <embed src="./{{< meta bibtex >}}" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;" />
</div>
```
